#
# https://qiita.com/dmystk/items/3f82b1eb763c9b9b47e8
#
CC := @gcc

TARGET := a.out

SRCDIR := src

OUTDIR := out
BINDIR := $(OUTDIR)/.bin
OBJDIR := $(OUTDIR)/.obj
DEPDIR := $(OUTDIR)/.dep

CFLAGS := -fPIC $(shell pkg-config --cflags geany)

#DEPFLAGS = -MT $@ -MMD -MP -MF $(DEPDIR)/$*.d
DEPFLAGS = -shared $(shell pkg-config --libs geany)

SRCS := $(wildcard $(SRCDIR)/*.c)
OBJS := $(addprefix $(OBJDIR)/, $(notdir $(SRCS:.c=.o)))
DEPS := $(addprefix $(DEPDIR)/, $(notdir $(SRCS:.c=.d)))

$(BINDIR)/$(TARGET): $(OBJS) | $(BINDIR)
	$(CC) $(CFLAGS) -o $@ $^

$(OBJDIR)/%.o: $(SRCDIR)/%.c $(DEPDIR)/%.d | $(OBJDIR) $(DEPDIR)
	$(CC) $(DEPFLAGS) $(CFLAGS) -c -o $@ $<

# The empty rule is required to handle the case where the dependency file is deleted.
$(DEPS):

include $(wildcard $(DEPS))

$(BINDIR):
	@mkdir -p $@

$(OBJDIR):
	@mkdir -p $@

$(DEPDIR):
	@mkdir -p $@

.PHONY: all
all: clean $(TARGET)

.PHONY: clean
clean:
	@-rm -rf $(OUTDIR)